FLUME-512: Must rethrow Throwables in RollSink - some throwables such as NoClassDefFoundError are Errors which are not exceptions and would inadvertently get swallowed.